
services:
  servico-banco:
    image: mysql:8.0
    container_name: identity-banco
    restart: always
  
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: identity_db        
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - dados-salvos:/var/lib/mysql
volumes:
  dados-salvos: